'use server';
/**
 * @fileOverview A Genkit flow that streams AI responses and collects them into a single output.
 *
 * - streamAIResponse - A function that handles the AI streaming process, collecting all generated tokens.
 * - StreamAIResponseInput - The input type for the streamAIResponse function.
 * - StreamAIResponseOutput - The return type for the streamAIResponse function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AIMessageSchema = z.object({
  role: z.enum(['user', 'model']),
  parts: z.array(z.object({ text: z.string() })),
});

const AIProxyRequestSchema = z.object({
  contents: z.array(AIMessageSchema),
  generationConfig: z.object({
    temperature: z.number().optional(),
    topP: z.number().optional(),
    topK: z.number().optional(),
    maxOutputTokens: z.number().optional(),
    stopSequences: z.array(z.string()).optional(),
  }).optional(),
  systemInstruction: z.object({
    parts: z.array(z.object({ text: z.string() })),
  }).optional(),
});

export type StreamAIResponseInput = z.infer<typeof AIProxyRequestSchema>;

const StreamAIResponseOutputSchema = z.object({
  text: z.string().describe('The complete text generated by the AI model.'),
});

export type StreamAIResponseOutput = z.infer<typeof StreamAIResponseOutputSchema>;

export async function streamAIResponse(input: StreamAIResponseInput): Promise<StreamAIResponseOutput> {
  return streamAIResponseFlow(input);
}

const streamAIResponseFlow = ai.defineFlow(
  {
    name: 'streamAIResponseFlow',
    inputSchema: AIProxyRequestSchema,
    outputSchema: StreamAIResponseOutputSchema,
  },
  async (input) => {
    const genkitPrompt = input.contents.map(msg => ({
      role: msg.role,
      parts: msg.parts.map(p => ({ text: p.text })),
    }));

    const genkitConfig = {
      temperature: input.generationConfig?.temperature,
      topP: input.generationConfig?.topP,
      topK: input.generationConfig?.topK,
      maxOutputTokens: input.generationConfig?.maxOutputTokens,
      stopSequences: input.generationConfig?.stopSequences,
    };

    const genkitSystemInstruction = input.systemInstruction?.parts?.map(p => ({
      text: p.text,
    }));

    let fullText = '';
    const { stream, response } = await ai.generateStream({
      model: ai.model('googleai/gemini-2.5-flash'), // Explicitly use the model
      prompt: genkitPrompt,
      config: genkitConfig,
      systemInstruction: genkitSystemInstruction,
    });

    for await (const chunk of stream) {
      if (chunk.text) {
        fullText += chunk.text;
      }
    }
    await response;

    return { text: fullText };
  }
);
